### ISSUE TITLE
Add docker with Vagrant or remove Vagrant

### ISSUE THREAD

**Issue by SandHilt** [c4milo/node-inotify#64]
Hey,
Vagrant is very useful but he is heavy if you compare with [Docker](https://www.docker.com).

Add this:
Dockerfile
```dockerfile
FROM node:6

ENV NPM_CONFIG_LOGLEVEL warn

WORKDIR /usr/src/inotify
COPY . .

RUN yarn add -D node-gyp
```
docker-compose.yml
```yml
version: '2'

services: 
  node:
    build: .
    command: yarn test
```
And run this:
```bash
$ docker-compose up
```

If you wish keep Vagrant, you can use docker like provider (Vangrant version >= 1.6).
[Here.](https://www.vagrantup.com/docs/provisioning/docker.html)
